version: '3'
services:
    grafana:
        image: grafana/grafana
        ports:
            - "3000:3000"
        container_name: argos-server-grafana
    influxdb:
        image: influxdb
        ports:
            - "8086:8086" 
        container_name: argos-server-influxdb
        environment:
            - INFLUXDB_DB="monitoring"
